[tool.poetry]
name = "gram2vec"
version = "0.1.0"
description = ""
authors = ["Eric Sclafani"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
demoji = "^1.1.0"
numpy = "^1.24.0"
pandas = "^1.5.2"
scikit-learn = "^1.2.0"
spacy = "^3.4.4"
matplotlib = "^3.6.2"
seaborn = "^0.12.1"
ipykernel = "^6.19.4"
nltk = "^3.8"
toml = "^0.10.2"
pytest = "^7.2.0"
more-itertools = "^9.0.0"
ipdb = "^0.13.11"
ijson = "^3.1.4"
plotly = "5.11.0"
nbformat = "^5.7.1"
metric-learn = "^0.6.2"


[tool.poetry.group.dev.dependencies]
notebook = "^6.5.2"
jupyter = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = [
  ".", "gram2vec", 
]